import { Users } from "lucide-react";
import { FC, useState } from "react";
import { UseFormReturn } from "react-hook-form";
import { toast } from "sonner";

import {
  ALL_MANAGED_TAG_IDS,
  GENDER_MAP,
  IDENTIFIER_FIELD_MAP,
  RC_TYPE_TO_TAG_ID,
  parseKutumbaDate,
} from "@/lib/kutumba-mappings";

import { Button } from "@/components/ui/button";

import FillFromKutumbaSheet from "@/components/kutumba/FillFromKutumbaSheet";

import { kutumbaConfig } from "@/config";
import type { KutumbaMember } from "@/types/kutumba";

type PatientRegistrationFormProps = {
  form: UseFormReturn;
  facilityId?: string;
  patientId?: string;
  submitForm?: () => void;
};

/**
 * Finds the identifier slot in the form arrays and sets or clears its value.
 * Searches required_identifiers, optional_identifiers, and autogenerated_identifiers.
 */
function fillIdentifiers(form: UseFormReturn, member: KutumbaMember) {
  const identifierGroups = [
    "required_identifiers",
    "optional_identifiers",
    "autogenerated_identifiers",
  ] as const;

  for (const { configId, field } of IDENTIFIER_FIELD_MAP) {
    if (!configId) continue;

    const value = member[field] ?? "";

    for (const group of identifierGroups) {
      const entries: { config: string; value?: string }[] =
        form.getValues(group) ?? [];
      const idx = entries.findIndex((entry) => entry.config === configId);
      if (idx !== -1) {
        form.setValue(`${group}.${idx}.value`, value, { shouldDirty: true });
        break;
      }
    }
  }
}

const PatientRegistrationForm: FC<PatientRegistrationFormProps> = ({
  form,
  patientId,
  submitForm,
}) => {
  const [sheetOpen, setSheetOpen] = useState(false);

  const handleMemberSelect = (
    member: KutumbaMember,
    allMembers: KutumbaMember[],
  ) => {
    const opts = { shouldDirty: true };

    // Set or clear all Kutumba-fillable fields based on the selected member
    form.setValue("name", member.name || "", opts);

    const formatPhone = (phone: string) => "+91" + phone.replace("+91", "");

    const currentPhone: string = form.getValues("phone_number") ?? "";
    if (!currentPhone || currentPhone === "+91") {
      form.setValue(
        "phone_number",
        member.mobile_no ? formatPhone(member.mobile_no) : "",
        opts,
      );
    }

    // Use family head's phone as emergency contact for non-head members
    const HEAD_RELATIONS = ["self", "head", "family head"];
    const isHead = HEAD_RELATIONS.includes(member.relation_name?.toLowerCase());

    if (!isHead) {
      const familyHead = allMembers.find((m) =>
        HEAD_RELATIONS.includes(m.relation_name?.toLowerCase()),
      );
      const headPhone = familyHead?.mobile_no;

      if (headPhone) {
        form.setValue("emergency_phone_number", formatPhone(headPhone), opts);
        form.setValue(
          "emergency_phone_number_same_as_phone_number",
          false,
          opts,
        );
      } else {
        form.setValue("emergency_phone_number", "", opts);
        form.setValue(
          "emergency_phone_number_same_as_phone_number",
          true,
          opts,
        );
      }
    } else {
      // For the family head, reset to default behavior
      form.setValue("emergency_phone_number_same_as_phone_number", true, opts);
    }

    const dob = member.date_of_birth
      ? parseKutumbaDate(member.date_of_birth)
      : undefined;
    if (dob) {
      form.setValue("age_or_dob", "dob", opts);
      form.setValue("date_of_birth", dob, opts);
    } else {
      form.setValue("date_of_birth", undefined, opts);
    }

    const mappedGender = member.gender ? GENDER_MAP[member.gender] : undefined;
    form.setValue("gender", mappedGender ?? "", opts);

    const cleanAddress = member.address
      ? member.address
          .replace(/\r\n/g, ", ")
          .replace(/\r/g, "")
          .replace(/\.\s*,/g, "")
          .replace(/,\s*,/g, ",")
          .replace(/^[,\s]+|[,\s]+$/g, "")
      : "";
    form.setValue("address", cleanAddress, opts);
    form.setValue("permanent_address", cleanAddress, opts);

    form.setValue(
      "pincode",
      member.pincode ? Number(member.pincode) : undefined,
      opts,
    );

    // Auto-select tags based on member data
    // Remove all previously managed tags, then re-apply based on current member
    const currentTags: string[] = form.getValues("tags") ?? [];
    const filteredTags = currentTags.filter(
      (id) => !ALL_MANAGED_TAG_IDS.includes(id),
    );
    const newTags = [...filteredTags];

    if (member.rc_type) {
      const tagId = RC_TYPE_TO_TAG_ID[member.rc_type.toUpperCase()];
      if (tagId) newTags.push(tagId);
    }

    if (member.education_id && kutumbaConfig.studentUnverifiedTagId) {
      newTags.push(kutumbaConfig.studentUnverifiedTagId);
    }

    if (member.disability_applicant_no && kutumbaConfig.pwdUnverifiedTagId) {
      newTags.push(kutumbaConfig.pwdUnverifiedTagId);
    }

    form.setValue("tags", newTags, opts);

    fillIdentifiers(form, member);

    toast.success(`Details filled from Kutumba for ${member.name}`);

    if (kutumbaConfig.autoSubmitOnFill) {
      toast.info("Auto-submitting form after filling from Kutumba");
      submitForm?.();
    }
  };

  if (patientId) return null;

  return (
    <div className="care-kutumba-fe-container flex justify-end w-full">
      <Button
        type="button"
        variant="outline"
        className="w-full text-primary border-primary"
        onClick={() => setSheetOpen(true)}
      >
        <Users className="size-4" />
        Fill from Kutumba
      </Button>

      <FillFromKutumbaSheet
        open={sheetOpen}
        onOpenChange={setSheetOpen}
        onMemberSelect={handleMemberSelect}
      />
    </div>
  );
};

export default PatientRegistrationForm;
